### ISSUE TITLE
Guidance on Two-Way Binding on a Model property

### ISSUE THREAD

**Issue by SSchulze1989** [klemmchr/MvvmBlazor#100]
### Question

Hello,
I am just starting out with blazor and your Mvvm library is already helping me a lot getting on.
I just have a question if you could explain how to best handle two-way bindings on properties that are bound from the model.
For example i have a model and a viewmodel like below.
How would i go best to integrate notification into that view model?

Cheers
Simon

### Code sample

```C#
public class Model 
{
    public string Name { get; set; }
}

public class ViewModel : ViewModelBase
{
    private Model _model;

    public string Name 
    { 
        get  => _model.Name; 
        set 
        {
            _model.Name = value;
            OnPropertyChanged(nameof(Name));
        }
    }
}
```

### Version

6.0.3

### Are you using Blazor WASM or Blazor Server?

Balzor Server

**Comment by SSchulze1989** [comment]
To elaborate, i was looking for something less verbose than:
```
public string Name
    {
        get => _model.Name;
        set
        {
            _model.Name = value;
            OnPropertyChanged(nameof(Name));
        }
    }
```

**Comment by klemmchr** [comment]
Currently there is no built-in solution for this. Could you elaborate why you want a binding on a sub model? Is the model changed externally outside of the view model?

**Comment by SSchulze1989** [comment]
The Model is part of my Business Logic that communicates with a REST Api. The ViewModel should enable modifying the Model and then sending a request back to the Api without having to map in between the models.

**Comment by klemmchr** [comment]
This could only be achieved by having a binding on a type that implements `INotifyPropertyChanged` and then listen to changed events on this end. Would be a new feature and possibly be a bit tedious to implement because it would break with current behavior. Would that suit you?

**Comment by SSchulze1989** [comment]
Ah I think i did not get that across correctly.
I do not want the Model to notify on the ViewModel. The ViewModel would still invoke the notification itself but the changes should be reflected on the Model so that the Business logic can handle the requests.

So I want the Model to hold the state for the api client and the ViewModel for interaction with the component.
I updated my code example a little so maybe it gets clearer.

**Comment by SSchulze1989** [comment]
Thank you very much for the quick response and the change.
Exactly what i needed and working like a charm!
