### ISSUE TITLE
Blazor Server - No Startup

### ISSUE THREAD

**Issue by jtsmithit** [klemmchr/MvvmBlazor#105]
### Question

The startup class doesn't exist when you create a new blazor server project, and .AddMvvm() is not available in program using builder.Services.AddMvvm().

How do I start using this library in this case?

### Version

0.7.1-preview9

### Are you using Blazor WASM or Blazor Server?

Blazor Server

**Comment by klemmchr** [comment]
I've just created a new .NET 6 Blazor Server app (also not using a `Startup` class) added the package reference and was able to use `builder.Services.AddMvvm()`. Are you sure you properly installed the package?

**Comment by jtsmithit** [comment]
I installed it via the nuget package manager in visual studio. It shows that it is installed and the namespace is available.

**Comment by jtsmithit** [comment]
![Screenshot 2022-05-27 170755](https://user-images.githubusercontent.com/73365133/170798963-c546fb28-f30d-4485-a705-2d6d1ad2f67e.png)

**Comment by klemmchr** [comment]
Could you provide a reproduction for this?

**Comment by klemmchr** [comment]
You installed the wrong package. `BlazorMVVM` is not [`MvvmBlazor`](https://www.nuget.org/packages/MvvmBlazor)

**Comment by jtsmithit** [comment]
Well that certainly explains things. My bad!
