### ISSUE TITLE
MvvmComponentBase does not call AsyncServiceScope.DisposeAsync()

### ISSUE THREAD

**Issue by oleneveu** [klemmchr/MvvmBlazor#110]
### Bug description

When a service used within the scope of the `MvvmComponentBase `implements `IAsyncDisposable`, its `DisposeAsync()` method is not called when the component is disposed.

### Expectation

`MvvmComponentBase `should implement `IAsyncDisposable `and call `_scope.DisposeAsync()` from its `DisposeAsync()` method.

### Code sample

```C#
public abstract class MvvmComponentBase : ComponentBase, IDisposable
```

### Version

6.0.5

### Are you using Blazor WASM or Blazor Server?

Blazor WASM

### What operation system are you working with?

Windows

**Comment by klemmchr** [comment]
Good catch, interestingly enough I took the implementation from `OwningComponentBase` and it also does not implement `IAsyncDisposable`. I don't really understand why tho.
