### ISSUE TITLE
Razor page dispose not firing when inheriting from view model

### ISSUE THREAD

**Issue by krugertech** [klemmchr/MvvmBlazor#119]
### Description

Hi There. 

Thanks for this great project.

I found a problem (or is it by design?) where a razor page's dispose method will not fire when inheriting from a view model, even if the view model does not implement dispose itself. 

For example;  the code below displays a razor component inheriting from a view model but also implementing IDisposable. 
As long as the razor component is inheriting from an Mvvm view model, the dispose implementation will never be called here.

    @page "/"
    @using MvvmBlazor.Components;
    @inherits MvvmComponentBase<TestViewModel>
    @implements IDisposable
    
    @code {
        void IDisposable.Dispose()
        {
            // NOTE: as long as @inherits is not commented out, this method will not fire.
        }
    }

I've put together a sample project demonstrating this behavior [here](https://github.com/krugertech/Blazor-Inherit-VM-Disables-Razor-Page-Dispose) for you.

**Comment by klemmchr** [comment]
`MvvmComponentBase` implements `IDisposable` and therefore your custom implementation will not work. Implementing IDisposable implicitly is not a good idea either. If you want to dispose your own resources in your component you can override `Dispose(bool disposing)`.

**Comment by krugertech** [comment]
Thanks for the feedback. I'll look at overriding Dispose as suggested. 

Note that I did see that swapping out IDisposable with IAsyncDisposable worked. 

>>  Implementing IDisposable implicitly is not a good idea either.
Could you elaborate why?

**Comment by klemmchr** [comment]
> Note that I did see that swapping out IDisposable with IAsyncDisposable worked.

It's a different interface and it's not implemented by `MvvmComponentBase` so this behavior is expected.

> Implementing IDisposable implicitly is not a good idea either.

Sorry, I meant explicitly. Your current problem outlines why this is a problem. If you inherit from a class and then explicitly implement an interface that has already been implemented implictly by a derived class you won't notice that you accidentally tried to override the base implementation. But as you discovered, you cannot override the implicit implementation using an explicit in a derived class.  
It's even worse when doing it the opposite way: having an explicit implementation in a base class that is not sealed makes it impossible for derived classes to override the members.  
There is also rule [CA1033](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1033) describing this anti-pattern. In general I would advise to not use explicit implementations unless it's really needed (e.g. two interfaces with the same member signature) or you want to hide some internal things to the owner of the class instance.

**Comment by krugertech** [comment]
I see. This makes sense now. 
Thanks again for the feedback.
