### ISSUE TITLE
How can an MvvmComponent implement IAsyncDisposable?

### ISSUE THREAD

**Issue by pm64** [klemmchr/MvvmBlazor#121]
### Question

I want my MvvmComponent to implement IAsyncDisposable, and do some cleanup in a DisposeAsync() method.

But it appears the source generator automatically adds a DisposeAsync() to MvvmComponents, so I get:

```
error CS0111: Type 'MyComponent' already defines a member called 'DisposeAsync' with the same parameter types
```

What's the recommended way around this?

### Version

6.0.6

### Are you using Blazor WASM or Blazor Server?

Blazor WASM

**Comment by pm64** [comment]
Suggestion: make the generated DisposeAsync() a partial method to create an extensibility point.

**Comment by pm64** [comment]
Another related concern.. According to [Microsoft docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-7.0#component-disposal-with-idisposable-and-iasyncdisposable), "Components shouldn't need to implement IDisposable and IAsyncDisposable simultaneously. If both are implemented, the framework only executes the asynchronous overload."

What I gather from this is that because of the DisposeAsync() method added to MVVM components by the code generator, if the developer creates a component that implements IDisposable, their Dispose() method will be ignored. Is this the case?

**Comment by klemmchr** [comment]
> Suggestion: make the generated DisposeAsync() a partial method to create an extensibility point.

There is a protected virtual method named [`DisposeAsyncCore`](https://github.com/klemmchr/MvvmBlazor/blob/master/src/MvvmBlazor.CodeGenerators/Components/MvvmComponentGenerator.cs#L263) that can be overriden for this purpose.

> What I gather from this is that because of the DisposeAsync() method added to MVVM components by the code generator, if the developer creates a component that implements IDisposable, their Dispose() method will be ignored. Is this the case?

The DisposeAsync Method calls both, `DiposesAsyncCore` and `Dispose`. So even when you're only overriding the sync `Dispose` method your resources will be disposed properly.

**Comment by pm64** [comment]
Thanks @klemmchr, appreciated as always.
