### ISSUE TITLE
Issue in MvvmComponentBase validatebinding

### ISSUE THREAD

**Issue by danglingneuron** [klemmchr/MvvmBlazor#39]
I have a base view model with a property I want to bind on. The following code throws an exception because the declaring type is the base class and the viewmodel is the sub class. Is there a specific reason you have this condition?

if (p.DeclaringType != viewModel.GetType())
                throw new BindingException($"Cannot find property {p.Name} in type {viewModel.GetType().FullName}");

**Comment by klemmchr** [comment]
This code should check for the existence of the property on the view model. However, I never considered inheritance for this check. Gonna fix this soon.
