### ISSUE TITLE
ViewModelBase doesn't implement IAsyncDisposable

### ISSUE THREAD

**Issue by BrentCarter** [klemmchr/MvvmBlazor#43]
Hi. Awesome library!  Thanks for making this public so we can learn form and use it.  I'm not sure if you want people suggesting issues but I noticed ViewModelBase implements IDisposable but not IAsyncDisposable.  I think Blazor didn't used to implement IAsyncDisposable for components but I think it does now...  It seems like you might want to add that.  Thanks again!

**Comment by klemmchr** [comment]
> I'm not sure if you want people suggesting issues

Sure, this is what GitHub is for 😉 

>  I think Blazor didn't used to implement IAsyncDisposable for components but I think it does now

Gonna have a look into it. Might result in a breaking change but not sure atm.
