### ISSUE TITLE
Need documentation on the need for sealing the lifecycle methods in MvvmComponentBase<T>

### ISSUE THREAD

**Issue by MarkStega** [klemmchr/MvvmBlazor#46]
MvvmComponentBase has accessible lifecycle methods. It certainly isn't clear why MvvmComponentBase[T] lifecycle methods are sealed preventing their override in a Blazor component that inherits from that class. I can see why one must call the base implementation of the methods since they are not simple virtuals. If they must remain sealed then documentation is needed as to why, and if they can be opened, then documentation on the need to call the base implementation is also needed.

**Comment by klemmchr** [comment]
Sorry for the late response. Actually there is no real reason why they are sealed. Probably I sealed them to prevent people from messing with them, but since it's common sense to call the base method, there is no real reason to have it like that. I'm going to unseal them.
