### ISSUE TITLE
Disposing ViewModel automatically in MVVMComponentBase

### ISSUE THREAD

**Issue by deveshbahuguna** [klemmchr/MvvmBlazor#55]
Hi Folks,
I was using this library and wanted to unregister some events inside Dispose method of VIewModel but could not find a best way to call it.
So I did some changes inside MVVMComponentBase to call the Dispose method of the Binding Context if it is disposable.

Should I raise a PR as this might be useful for others as well or do you have any better suggestion?

Below is the PR: https://github.com/klemmchr/MvvmBlazor/pull/56

**Comment by klemmchr** [comment]
The view model gets injected into the component via DI. Injected services should never be disposed as [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#disposal-of-services) say:

> The container calls Dispose for the IDisposable types it creates. Services resolved from the container should never be disposed by the developer. If a type or factory is registered as a singleton, the container disposes the singleton automatically.

This means that the component should never dispose the view model. Just implementing IDisposable in your view model is enough to make this work.

**Comment by deveshbahuguna** [comment]
@klemmchr  You are right as per the documentation one should not call Dispose but if you look at the example provided by microsoft, the dispose method is called on each refresh of the page but why would one do that with MVVM? 

"The debug console shows the following output after each refresh of the Index page:"
