### ISSUE TITLE
Feature request: "MvvmOwningComponentBase" which inherit from OwningComponentBase

### ISSUE THREAD

**Issue by deveshbahuguna** [klemmchr/MvvmBlazor#58]
Raising new issue as MvvmOwningComponentBase could be added as a seperate feature

@klemmchr we could have one more class "MvvmOwningComponentBase" which inherit from OwningComponentBase  and i don't think this will be an anti pattern as you have already created MvvmComponentBase which derive from Blazor's Component base similarly we could have MvvmOwningComponentBase deriving from owning component base.

_Originally posted by @deveshbahuguna in https://github.com/klemmchr/MvvmBlazor/issues/57#issuecomment-986784025_

**Comment by klemmchr** [comment]
Will be addressed via #57
