### ISSUE TITLE
Update Service Locator Pattern in MVVMComponentBase to Constructor Injection

### ISSUE THREAD

**Issue by deveshbahuguna** [klemmchr/MvvmBlazor#60]
In MVVMComponentBase class the dependency WeakEventManager and BindingFactory are resolved by Service Locator Pattern which as per the mentioned URL is incorrect.

URL:  "https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/"

The correct way should be constructor injection instead.

**Comment by klemmchr** [comment]
Using a service locator is absolute fine in this context and is required to resolve services. Constructor injection is not possible when creating a base component.

**Comment by deveshbahuguna** [comment]
@klemmchr  I think we can do something like the below code
```
protected internal MvvmComponentBase(IWeakEventManagerFactory weakEventManagerFactory, IBindingFactory bindingFactory)
        {
            _bindingFactory =  bindingFactory;
            _weakEventManagerFactory = weakEventManagerFactory;
            _weakEventManager = _weakEventManagerFactory.Create();     
        }
```

the above parameters can be passed to MvvmComponentBase by the derived class
