### ISSUE TITLE
Is there a way to InvokeAsync within the view model?

### ISSUE THREAD

**Issue by tancyew** [klemmchr/MvvmBlazor#91]
I'm currently working with blazor server apps, wondering if there is a way for me to invoke async within the ViewModel itself?

**Comment by tancyew** [comment]
Appreciate your prompt reply.

Personally, i'm currently having connection monitoring service running in the background thread, then proceed in raising and event as to wether the remote service is up or down, then I'll change the color and icon to indicate different connection statuses. I noticed that the event is raised on background thread, thus having a need to InvokeAsync to notify the UI of the changes.

**Comment by klemmchr** [comment]
If you leave a code sample I could debug it later to see the exact problem. Generally you don't want to call `InvokeAsync` manually because this should be handled by the library. Changing the value of a Notify Property invokes `StateHasChanged()` and then schedules a rerendering of the component.

**Comment by tancyew** [comment]
Okay let me try to prepare over the weekend, thanks!

I totally agree with you.

**Comment by klemmchr** [comment]
Closing as stale

**Comment by tancyew** [comment]
Hi sorry for the late reply. I've manage to put a workaround on regarding this issue on my project, but would still love to share a demo project for you to have a look.

Basically, within the view model, if the changes coming from another thread (e.g. timer thread) and the changes won't be propagated to the UI. I might be wrong on this. You can check the counter page for the demo.

If we start the timer normally without raising an event to the .razor page to call InvokeAsync(StateHasChanged) the counter will not change until the timer is stopped.

Cheers,
Chris

[DemoApp 2.zip](https://github.com/klemmchr/MvvmBlazor/files/8897857/DemoApp.2.zip)
!

**Comment by tancyew** [comment]
sorry, I've just noticed the library does have @Bind method that I've not taken advantage of! That might help to resolve a lot of boilerplate code. 

truly sorry as I've missed that out.

Can i use the @Bind on Observable Collection as well? Will that be possible?

**Comment by klemmchr** [comment]
> sorry, I've just noticed the library does have @Bind method that I've not taken advantage of! That might help to resolve a lot of boilerplate code.

That explains a lot 😅

> Can i use the @Bind on Observable Collection as well? Will that be possible?

You might wanna take a loot at the [Readme](https://github.com/klemmchr/MvvmBlazor#collection-bindings) since it answers probably most of your questions.

**Comment by tancyew** [comment]
thanks! sorry i don't know how i missed that :(.

I'll try around with that thanks for making a great library!
