### ISSUE TITLE
After upgrade to version 6.0.3 scoped dependency injection is not working properly

### ISSUE THREAD

**Issue by xDDDx** [klemmchr/MvvmBlazor#98]
### Bug description

We are getting `GetAuthenticationStateAsync was called before SetAuthenticationState` after upgrade to version 6.0.3

Our Authentication Service is registred as scoped service and is injected on the Layout.razor page and in ViewModel. We can see, that there are two different instances. With version 2.0.0 it works as expected and the instances are the same

### Expectation

Scoped service instances are the same for all injections on current request

### Code sample

```C#
public class ScopedService { }
// Register service
builder.Services.AddScoped<ScopedService>();
// make a component and the view model
@inherits MvvmBlazor.Components.MvvmComponentBase<MvvmComponentViewModel>
<h1>MvvmComponent injected ScopedService Hash: @BindingContext.GetInjectedServiceHash()</h1>

//---------------------------
    public class MvvmComponentViewModel : ViewModelBase
    {
        private readonly ScopedService _scopedService;

        public MvvmComponentViewModel(ScopedService scopedService)
        {
            _scopedService = scopedService;
        }

        public int GetInjectedServiceHash()
        {
            return _scopedService.GetHashCode();
        }
    }

// inject service on razor page and show the HashCodes
@inject ScopedService _scopedService
<h1>Razor injected ScopedService Hash: @_scopedService.GetHashCode()</h1>
<MvvmComponent/>
```

### Version

6.0.3

### Are you using Blazor WASM or Blazor Server?

Balzor Server

### What operation system are you working with?

Windows

**Comment by klemmchr** [comment]
There was a breaking change from `2.x` to `6.x` that makes ViewModels act like a `OwningComponentBase` where services injected into it are scoped to the scope of the component. 

This is also described in the [Readme](https://github.com/klemmchr/MvvmBlazor#viewmodel).

> If you register a view model as scoped it will be tied to the lifetime of the component and disposed when the component is disposed. This allows you to inject scoped services that should be short lived (e.g. a DbContext) without the need for using a factory.

> Note: Some services need to be resolved from the root service provider (e.g. NavigationManager). To do this you can access the root service provider via the RootServiceProvider property.

This has been done to ensure that disposing of services happens properly in the scope of the component. If you want to use a scoped service where the lifetime of it is scoped to the lifetime of the `HttpContext` you can resolve the service from the `RootServiceProvider` inside of the view model.

**Comment by xDDDx** [comment]
Hmm, I understand. It is not optimal, but our project is not that big. The problem is, that most of our services are `HttpContext` scoped. So we use the `RootServiceProvider` a lot and now it is not that intuitive and clear.

It would be better, if there were the possibility to define custom scopes and not only `Singleton`, `Scoped` and `Transient`, but this is not possible. 

Please close the issue. And thanks for helping! ;)

PS: Nice work with code generator! I started also a small project for a smart code generated mapper

**Comment by klemmchr** [comment]
> It would be better, if there were the possibility to define custom scopes and not only Singleton, Scoped and Transient, but this is not possible.

Yes and because of this there is this scope pattern that has been introduced with `6.0.0`. Otherwise disposing would not work properly.
